name: Build
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: md RunResults
    - name: Build library
      run: dotnet build -c Release Combinatorics
    - name: Build executables
      run: |
        dotnet build -c Release Examples\Queens\PnBacktrackSlim
    - name: Run executables
      run: |
        .\Examples\Queens\PnBacktrackSlim\bin\Release\net8.0\PnBacktrackSlim.exe > RunResults\PnBacktrackSlim.txt
    - name: Copy build artifacts
      run: copy Combinatorics\bin\Release\*.nupkg RunResults
    - uses: actions/upload-artifact@v1
      with:
        name: KaosCombinatorics-Build
        path: RunResults